---
title: "Segundo taller"
output: html_document
date: "2024-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)


library(readxl)


condados <- read_excel("condados.xlsx", na ="NA")

Alabama <- condados %>% filter(.,estado == "Alabama")


```

```{r}
#Ajustar un modelo lineal multiple para explicar los valores de 'esp_vida' en los
#condados del estado que elefimos

#QUeremos ajustar un modelo que explique la esperanza de vida según el ingreso mediano de los hogares
#incluyendo también las demás variables explicativas

#Ajuste el modelo de regresion lineal múltiple

#pct_diabetes: 
#pct_obesidad
#pct_est_terc
#ing_med_hog
#pct_bpeso


mod <- lm(esp_vida ~ pct_diabetes + pct_obesidad + pct_est_terc + ing_med_hog + pct_bpeso, data = Alabama)

coef(mod)

#Ajustando el ingreso en miles de dolares

Alabama <- Alabama %>% mutate(imh = ing_med_hog/1000)


mod <- lm(esp_vida ~ pct_diabetes + pct_obesidad + pct_est_terc + imh + pct_bpeso, data = Alabama)

round(coef(mod),5)

#Cuanto vale el R**2?

summary(mod)

names(summary(mod))


#El modelo explica el 52% de la varianza de la esperanza de vida



#Realice el gráfico de Y_gorro contra e_gorro

y_gorro <- fitted(mod)



e_gorro <- residuals(mod)

Alabama <-  cbind(Alabama,y_gorro,e_gorro)

class(Alabama)

ggplot(data=Alabama, aes(x=y_gorro,y=e_gorro))+geom_point()

#+geom_smooth(method = "lm", se=F, col =2, size =2)




```


```{r}

#INFERENCIA

#Es el modelo significativo?


summary(mod)

#Es significativo con un F de 13.68 y un p-valor de 0.000000001
#En la hipotesis global esta diciendo que al menos uno es distinto de 0


#Analizando el summary para dos variables el p valor es menor al 0.05

#Cuantos grados de libertad?
# n-k-1 = 61


#QUe hace la fnción 'drop1' y  utilicela para obtener los estadisticos F de significacion individual para cada variable

help(drop1)

class(mod)

drop1(mod,test="F")


#¿Es posible afirmar que los coeficientes de las variables son simultaneamente cero?

mod2 <- lm(esp_vida ~  pct_obesidad + imh , data = Alabama)

mod2 <- update(mod, .~pct_obesidad + imh)

summary(mod2)

#Acá estoy comparando el modelo donde forcé a que las variables que quite tengan valor 0 contra el otro

anova(mod2,mod)

#Teniendo las variables obesidad e ingreso las otras variables no aportan al modelo.
#No rechazo Ho) donde los betas de las variables que quité valen 0


#p-valor en una F con 3,61 GL
1-pf(1.2632 , 3,61)



#Podemos decir que por cada unidad que aumenta el porcentaje de personas con obesidad la esperanza de vida del condado desciende un mes?


summary(mod2)

-0.094*12

#es -1.128 significativamente un mes?

confint(mod2)

c(confint(mod2)[2,1]*12,confint(mod2)[2,2]*12)

#el -1 está incluido en el intervalo


```


```{r}
#MÁS INFERENCIA

#Ho) B_pct_est_terc <= 0
#H1) B_pct_est_terc > 0


#Realice la predicción de la esperanza de vida para un condado con 35% de personas obesas 
#y un ingreso mediano de 50000

predict(mod2, Alabama)


```

